name: Daily update config

on:
  schedule:
    # 每天东京/北京时间 05:00 (UTC 20:00)
    - cron: '0 20 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch and transform to /Rewrite/config.yaml
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p Rewrite
          tmp="$(mktemp)"

          # 1) 拉取远程 YAML
          curl -fsSL "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/configfull.yaml" -o "$tmp"

          # 2) 在 proxy-groups 之前的范围内，把目标 proxies 段落改成 +proxies
          awk 'BEGIN{before_pg=1}
               /^[[:space:]]*proxy-groups:/ {before_pg=0}
               {
                 if (before_pg && $0 ~ /^[[:space:]]*proxies:[[:space:]]*$/) {
                   sub(/proxies:/, "+proxies:")
                 }
                 print
               }' "$tmp" > "${tmp}_step1"

          # 3) 删除 PProviders 到第二个分隔行之间的块（缩进无关）
          awk 'BEGIN{inblock=0;delims=0}
               {
                 if(inblock){
                   if($0 ~ /^##############################################$/){
                     delims++
                     if(delims==2){inblock=0; next} else {next}
                   }
                   next
                 }
                 if($0 ~ /^[[:space:]]*PProviders:.*&PProviders/){
                   inblock=1; delims=0; next
                 }
                 print
               }' "${tmp}_step1" > Rewrite/config.yaml

          rm -f "$tmp" "${tmp}_step1"

      - name: Commit and push
        shell: bash
        run: |
          git add Rewrite/config.yaml
          git commit -m "Auto update Rewrite/config.yaml" || echo "No changes to commit."
          git push